sudo: required
services: docker

notifications:
  email: false

script: bash build.sh

matrix:
  include:
    - name: "Build Alpine for ARM32"
      env: ARCH=arm32 IMAGE_ARCH=arm32v6 QEMU_ARCH=arm
    - name: "Build Alpine for ARM64"
      env: ARCH=arm64 IMAGE_ARCH=arm64v8 QEMU_ARCH=aarch64
    - name: "Build Alpine for AMD64"
      env: ARCH=amd64 IMAGE_ARCH=amd64

deploy:
  - provider: script
    script: bash build.sh deploy
    name: "Deploy Alpine for ARM32"
    env: ARCH=arm32 IMAGE_ARCH=arm32v6 QEMU_ARCH=arm
    on:
      repo: aytekinar/openblas-alpine
      branch: master
  - provider: script
    script: bash build.sh deploy
    name: "Deploy Alpine for ARM64"
    env: ARCH=arm64 IMAGE_ARCH=arm64v8 QEMU_ARCH=aarch64
    on:
      repo: aytekinar/openblas-alpine
      branch: master
  - provider: script
    script: bash build.sh deploy
    name: "Deploy Alpine for AMD64"
    env: ARCH=amd64 IMAGE_ARCH=amd64
    on:
      repo: aytekinar/openblas-alpine
      branch: master
